---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: ngix-svc
      nodePort: 30080
      name: ngix-svc
---
apiVersion: v1
kind: Service
metadata:
  name: tcpdump-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: tcpdump
  ports:
    - protocol: TCP
      port: 8080
      targetPort: tcpdump-svc
      nodePort: 30808
      name: tcpdump-svc
---      
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume-1
  labels:
    type: local
spec:
  storageClassName: silver
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data/"
---      
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume-2
  labels:
    type: local
spec:
  storageClassName: silver
  capacity:
    storage: 1Gi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: "/mnt/data/"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tcpd-pv-claim
spec:
  storageClassName: silver
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pv-claim
spec:
  storageClassName: silver
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app.kubernetes.io/name: nginx
spec:
  volumes:
    - name: shared-data
      persistentVolumeClaim:
        claimName: nginx-pv-claim
  containers:
    - name: nginx
      image: amitinfo2k/nginx:1.0.3
      ports:
        - containerPort: 80
          name: ngix-svc
      volumeMounts:
        - name: shared-data
          mountPath: /usr/share/nginx/html
---
apiVersion: v1
kind: Pod
metadata:
  name: test
  labels:
    app.kubernetes.io/name: tcpdump
spec:
  volumes:
    - name: shared-data
      persistentVolumeClaim:
        claimName: tcpd-pv-claim
  containers:
    - name: tcpdump-go
      image: amitinfo2k/tcpdump-go:1.0.0
      env:
        - name: PCAP_DIR
          value: /dump
      ports:
        - containerPort: 8080
          name: tcpdump-svc
      volumeMounts:
        - name: shared-data
          mountPath: /dump
