apiVersion: v1
kind: Service
metadata:
  name: tcpdump-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: tcpdump
  ports:
    - protocol: TCP
      port: 80
      targetPort: ngix-svc
      nodePort: 30080
---
apiVersion: v1
kind: Pod
metadata:
  name: tcpdump-pod
  labels:
    app.kubernetes.io/name: tcpdump
spec:
  volumes:
    - name: shared-data
      emptyDir: {}
  containers:
    - name: nginx
      image: amitinfo2k/nginx:1.0.3
      volumeMounts:
        - name: shared-data
          mountPath: /usr/share/nginx/html
      ports:
        - containerPort: 80
          name: ngix-svc
    - name: tcpdump-c
      image: amitinfo2k/tcpdump-ex:1.0.0
      volumeMounts:
        - name: shared-data
          mountPath: /dump
